"""Constants and utilities related to analysts configuration rules."""

# Define analyst configuration rules - single source of truth for metadata and rules
ANALYST_CONFIG_RULES = {
    "aswath_damodaran": {
        "display_name": "Aswath Damodaran",
        "description": "The Dean of Valuation",
        "investing_style": "Focuses on intrinsic value and financial metrics.",
        "factor_rules": "Valuation Gatekeeper. Veto if Price > 1.2x DCF Intrinsic Value.",
        "type": "analyst",
        "order": 0,
    },
    "ben_graham": {
        "display_name": "Ben Graham",
        "description": "The Father of Value Investing",
        "investing_style": "Deep Value.",
        "factor_rules": "Requires P/B < 1.5. (Note: Current Ratio > 2.0 checked via fundamentals).",
        "type": "analyst",
        "order": 1,
    },
    "bill_ackman": {
        "display_name": "Bill Ackman",
        "description": "The Activist Investor",
        "investing_style": "Quality + FCF Yield.",
        "factor_rules": "Evaluates Quality + FCF Yield. Focuses on market dominance and predictable cash flows.",
        "type": "analyst",
        "order": 2,
    },
    "cathie_wood": {
        "display_name": "Cathie Wood",
        "description": "The Queen of Growth Investing",
        "investing_style": "Growth + Momentum.",
        "factor_rules": "Aggressive if Revenue Growth > 20% (0.20). Ignore valuation metrics.",
        "type": "analyst",
        "order": 3,
    },
    "charlie_munger": {
        "display_name": "Charlie Munger",
        "description": "The Rational Thinker",
        "investing_style": "Quality Focus.",
        "factor_rules": "Veto power on Quality. Requires ROE > 15% (0.15) and ROIC > 10% (0.10). Veto if Altman Z-Score < 1.8.",
        "type": "analyst",
        "order": 4,
    },
    "michael_burry": {
        "display_name": "Michael Burry",
        "description": "The Big Short Contrarian",
        "investing_style": "Risk Divergence.",
        "factor_rules": "Flags 'Short' if price momentum is high but Quality factors are declining (Divergence).",
        "type": "analyst",
        "order": 5,
    },
    "mohnish_pabrai": {
        "display_name": "Mohnish Pabrai",
        "description": "The Dhandho Investor",
        "investing_style": "Low Risk Value.",
        "factor_rules": "Focuses on low P/E stocks with minimal downside risk (Low VaR/Max Drawdown).",
        "type": "analyst",
        "order": 6,
    },
    "peter_lynch": {
        "display_name": "Peter Lynch",
        "description": "The 10-Bagger Investor",
        "investing_style": "GARP (Growth At Reasonable Price).",
        "factor_rules": "Requires PEG Ratio < 1.0 (Approximated by P/E divided by Growth Rate).",
        "type": "analyst",
        "order": 6,
    },
    "phil_fisher": {
        "display_name": "Phil Fisher",
        "description": "The Scuttlebutt Investor",
        "investing_style": "Growth Efficiency.",
        "factor_rules": "Evaluates Growth Efficiency. R&D-to-Sales must be high (aim for top 20th percentile).",
        "type": "analyst",
        "order": 7,
    },
    "rakesh_jhunjhunwala": {
        "display_name": "Rakesh Jhunjhunwala",
        "description": "The Big Bull Of India",
        "investing_style": "Growth Momentum.",
        "factor_rules": "Focuses on strong revenue growth backed by technical volume/momentum.",
        "type": "analyst",
        "order": 8,
    },
    "stanley_druckenmiller": {
        "display_name": "Stanley Druckenmiller",
        "description": "The Macro Investor",
        "investing_style": "Momentum/Macro.",
        "factor_rules": "Focuses on RSI strength and distance from 200d MA (Technical Strength).",
        "type": "analyst",
        "order": 9,
    },
    "warren_buffett": {
        "display_name": "Warren Buffett",
        "description": "The Oracle of Omaha",
        "investing_style": "Value + Quality.",
        "factor_rules": "Veto power on Quality. Requires ROE > 15% (0.15) and ROIC > 10% (0.10). Veto if Altman Z-Score < 1.8.",
        "type": "analyst",
        "order": 10,
    },
    "technical_analyst": {
        "display_name": "Technical Analyst",
        "description": "Chart Pattern Specialist",
        "investing_style": "Focuses on chart patterns and market trends to make investment decisions, often using technical indicators and price action analysis.",
        "factor_rules": "Analyze price action, RSI, and MA distances.",
        "type": "analyst",
        "order": 11,
    },
    "fundamentals_analyst": {
        "display_name": "Fundamentals Analyst",
        "description": "Financial Statement Specialist",
        "investing_style": "Delves into financial statements and economic indicators to assess the intrinsic value of companies through fundamental analysis.",
        "factor_rules": "Analyze financial health, margins, and growth.",
        "type": "analyst",
        "order": 12,
    },
    "growth_analyst": {
        "display_name": "Growth Analyst",
        "description": "Growth Specialist",
        "investing_style": "Analyzes growth trends and valuation to identify growth opportunities through growth analysis.",
        "factor_rules": "Analyze revenue and EPS growth trends.",
        "type": "analyst",
        "order": 13,
    },
    "news_sentiment_analyst": {
        "display_name": "News Sentiment Analyst",
        "description": "News Sentiment Specialist",
        "investing_style": "Analyzes news sentiment to predict market movements and identify opportunities through news analysis.",
        "factor_rules": "Analyze sentiment from news sources.",
        "type": "analyst",
        "order": 14,
    },
    "sentiment_analyst": {
        "display_name": "Sentiment Analyst",
        "description": "Market Sentiment Specialist",
        "investing_style": "Gauges market sentiment and investor behavior to predict market movements and identify opportunities through behavioral analysis.",
        "factor_rules": "Analyze overall market sentiment.",
        "type": "analyst",
        "order": 15,
    },
    "valuation_analyst": {
        "display_name": "Valuation Analyst",
        "description": "Company Valuation Specialist",
        "investing_style": "Specializes in determining the fair value of companies, using various valuation models and financial metrics for investment decisions.",
        "factor_rules": "Calculate Intrinsic Value (DCF) and multiples.",
        "type": "analyst",
        "order": 16,
    },
}
